In [1]:
import sys
import numpy as np

### Lesson 7: Numpy Introduction A

In [ ]:
# Lower level explanation

"""
RAM -> No of bits your comp can store
To store 32 find the correct binary representation in order to store the data into your computer
2^n ---> how many decimal numbers u need
"""

### Lesson 8: Numpy Introduction B

In [ ]:
# Both 7 & 8 are binary representation crash course

In [ ]:
x = 5 # takes 20 bytes in python cuz it's simple to r & w. So it wraps all numbs as objects

In [2]:
np.int8 # Can create a number with only 8 bits, controls size

numpy.int8

In [ ]:
# Numpy is an array processing lang
# Python not for high level computing
# in python:
# l = [3,2,4]
# Python may put it in diff places in memory
#numpy would be contigous and only takes a certain amount of memory that we fixed
# Arrays in numpy take advantage of cpu funcs

### Lesson 9: Numpy Arrays

#### Basic numpy arrays

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4])

In [6]:
b = np.array([0,0.5,1,1.5,2])

In [7]:
a[0],a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

#### Array types

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [19]:
np.array([1,2,3,4], dtype = np.float)

<ipython-input-19-2949a392c07b>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4], dtype = np.float)


array([1., 2., 3., 4.])

In [20]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a','b','c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a':1}, sys])

In [24]:
d.dtype

dtype('O')

 #### Dimensions and shapes

In [25]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [26]:
A.shape

(2, 3)

In [27]:
A.ndim # 2 dimensions

2

In [28]:
A.size

6

In [29]:
B = np.array([ #3d
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim #3d

3

In [33]:
B.size # total counts of els

12

In [35]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
])

<ipython-input-35-0a6e4182752a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [36]:
C.dtype # type object

dtype('O')

In [37]:
C.ndim 

1

In [38]:
C.size # # shape : 2 , 2 elements.

2

In [39]:
type(C[0])

list

#### Indexing and slicing of matrices

In [40]:
# Square matrix
A = np.array([
    #0.1.2.
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])
#A[d1,d2,d3,d4]

In [41]:
A[1]

array([4, 5, 6])

In [42]:
A[1][0]

4

In [43]:
A[1,0]

4

In [45]:
A[0:2] # 0 up till 2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
A[:,:2] #want to select every row but from a column level only upto 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
A[:2,2:]

array([[3],
       [6]])

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
A[1] = np.array([10,10,10])

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [52]:
A[2] = 99

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [54]:
a = np.array([1,2,3,4])

In [55]:
a.sum()

10

In [56]:
a.mean()

2.5

In [57]:
a.std()

1.118033988749895

In [58]:
a.var()

1.25

In [59]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [60]:
A.sum()

45

In [61]:
A.mean()

5.0

In [62]:
A.std()

2.581988897471611

In [63]:
A.var()

6.666666666666667

In [64]:
A.sum(axis=0)

array([12, 15, 18])

In [65]:
A.sum(axis=1)

array([ 6, 15, 24])

In [66]:
A.mean(axis=0)

array([4., 5., 6.])

In [67]:
A.mean(axis=1)

array([2., 5., 8.])

In [68]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [69]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Lesson 10: Numpy Operations

#### Broadcasting and vectorized opertations

In [70]:
a = np.arange(4)

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a + 10

array([10, 11, 12, 13])

In [73]:
a * 10

array([ 0, 10, 20, 30])

In [74]:
a

array([0, 1, 2, 3])

In [75]:
a += 100 #plus equals actually modifies the array

In [77]:
a

array([100, 101, 102, 103])

In [78]:
l = [0,1,2,3]

In [79]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [87]:
a = np.arange(5)

In [88]:
a

array([0, 1, 2, 3, 4])

In [89]:
a + 20 # doesnt modify original, to modify original use +=s

array([20, 21, 22, 23, 24])

In [90]:
a

array([0, 1, 2, 3, 4])

In [82]:
b = np.array([10,10,10,10])

In [83]:
a + b

array([10, 11, 12, 13])

In [84]:
a * b

array([ 0, 10, 20, 30])

### Lesson 11: Numpy Boolean Arrays

#### Boolean arrays

In [91]:
a = np.arange(4)

In [92]:
a

array([0, 1, 2, 3])

In [93]:
a[[0, -1]]

array([0, 3])

In [94]:
a[[True, False, False, True]] # selects first and last - boolean style

array([0, 3])

In [95]:
a >= 2

array([False, False,  True,  True])

In [96]:
a[a >= 2]

array([2, 3])

In [97]:
a.mean()

1.5

In [98]:
a[a > a.mean()]

array([2, 3])

In [99]:
a[~(a > a.mean())]

array([0, 1])

In [100]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [101]:
a[(a >= 2) & (a % 2 == 0)]

array([2])

In [102]:
A = np.random.randint(100, size=(3,3))

In [103]:
A

array([[25, 88, 74],
       [19,  6, 48],
       [23, 66, 13]])

In [104]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([25, 74,  6, 23, 13])

In [105]:
A > 30

array([[False,  True,  True],
       [False, False,  True],
       [False,  True, False]])

In [106]:
A[A > 30]

array([88, 74, 48, 66])

### Lesson 12: Numpy Algebra and Size

#### Linear Algebra

In [107]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [108]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [109]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [110]:
A @ B # Cross prod

array([[20, 14],
       [56, 41],
       [92, 68]])

In [111]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [112]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#### Size of objects in memory

##### Int, Floats

In [115]:
# An int in python is 28 bytes
sys.getsizeof(1)

28

In [116]:
sys.getsizeof(10**100)

72

In [117]:
# Numpy sizes are smaller
np.dtype(int).itemsize

8

In [118]:
np.dtype(float).itemsize

8

##### Lists are even larger

In [119]:
sys.getsizeof([1])

64

In [120]:
np.array([1]).nbytes

8

##### And performance is also important

In [122]:
l = list(range(1000))

In [123]:
a = np.arange(1000)

In [125]:
%time np.sum(a ** 2)

CPU times: user 453 µs, sys: 646 µs, total: 1.1 ms
Wall time: 998 µs


332833500

In [126]:
%time sum([x ** 2 for x in l])

CPU times: user 984 µs, sys: 26 µs, total: 1.01 ms
Wall time: 1.01 ms


332833500

##### Useful numpy functions

##### random

In [128]:
np.random.random(size = 2)

array([0.53587975, 0.23377743])

In [129]:
np.random.normal(size = 2)

array([-0.81011705,  0.95890915])

In [130]:
np.random.rand(2, 4)

array([[0.2320439 , 0.82511981, 0.91152363, 0.27199433],
       [0.82075345, 0.86619843, 0.72979265, 0.12208138]])

##### arange

In [131]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [133]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##### reshape

In [135]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##### linspace

In [137]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [138]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [139]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

##### zeros, ones, empty

In [140]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [141]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.zeros((3,3), dtype=np.int)

<ipython-input-142-fcc7bc85b3bb>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3,3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [143]:
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [144]:
np.empty(5)

array([1., 1., 1., 1., 1.])

##### identity and eye

In [145]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
np.eye(8,4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
np.eye(8,4, k = -3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [150]:
"Hello world"[6]

'w'